import type { Components, Theme } from '@mui/material';

import {
  getAccordionStyles,
  getAccordionSummaryStyles,
  getAccordionDetailsStyles,
  getAlertStyles,
  getButtonStyles,
  getCheckboxStyles,
  getInputStyles,
  getInputLabelStyles,
  getLinearProgressStyles,
  getMenuStyles,
  getMenuItemStyles,
  getModalStyles,
  getDialogStyles,
  getPopoverStyles,
  getRadioStyles,
  getSelectStyles,
  getAutocompleteStyles,
  getIconButtonStyles,
  getSliderStyles,
  getSwitchStyles,
  getTabsStyles,
  getTabStyles,
  getCssBaselineStyles,
  getLinkStyles,
  getTypographyStyles,
  getTooltipStyles,
  getPaginationStyles,
  getFormHelperTextStyles,
  getDividerStyles,
  getPaperStyles,
  getCircularProgressStyles,
  getDrawerStyles,
  getSnackbarStyles,
} from './styles';
import { getCardContentStyles } from './styles/card';

const getComponentStyles = (theme: Theme): Components => ({
  MuiAccordion: getAccordionStyles(theme),
  MuiAccordionSummary: getAccordionSummaryStyles(theme),
  MuiAccordionDetails: getAccordionDetailsStyles(theme),
  MuiAlert: getAlertStyles(theme),
  MuiButton: getButtonStyles(theme),
  MuiIconButton: getIconButtonStyles(theme),
  MuiCheckbox: getCheckboxStyles(theme),
  MuiTextField: getInputStyles(theme),
  MuiInputLabel: getInputLabelStyles(theme),
  MuiLinearProgress: getLinearProgressStyles(theme),
  MuiMenu: getMenuStyles(theme),
  MuiMenuItem: getMenuItemStyles(theme),
  MuiModal: getModalStyles(theme),
  MuiDialog: getDialogStyles(theme),
  MuiPopover: getPopoverStyles(theme),
  MuiRadio: getRadioStyles(theme),
  MuiSelect: getSelectStyles(theme),
  MuiAutocomplete: getAutocompleteStyles(theme),
  MuiSlider: getSliderStyles(theme),
  MuiSwitch: getSwitchStyles(theme),
  MuiTabs: getTabsStyles(theme),
  MuiTab: getTabStyles(theme),
  MuiCssBaseline: getCssBaselineStyles(theme),
  MuiLink: getLinkStyles(theme),
  MuiTypography: getTypographyStyles(theme),
  MuiTooltip: getTooltipStyles(theme),
  MuiPagination: getPaginationStyles(theme),
  MuiFormHelperText: getFormHelperTextStyles(theme),
  MuiDivider: getDividerStyles(theme),
  MuiPaper: getPaperStyles(theme),
  MuiCircularProgress: getCircularProgressStyles(theme),
  MuiDrawer: getDrawerStyles(theme),
  MuiSnackbar: getSnackbarStyles(theme),
  MuiCardContent: getCardContentStyles(theme),
});

export default getComponentStyles;
